# Generated by Django 3.2.3 on 2021-06-02 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('have_you_played_VR_before', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=6)),
            ],
        ),
    ]
